# Generated by Django 5.1 on 2024-08-31 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_wishlistmodel_date_added_wishlistmodel_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='amount',
            field=models.IntegerField(max_length=200, null=True),
        ),
    ]
