# Generated by Django 5.1 on 2024-08-31 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_shippingaddress_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='amount',
            field=models.IntegerField(null=True),
        ),
    ]
