# Generated by Django 5.1 on 2024-09-02 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_wishlistmodel_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myordersmodel',
            name='size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.inventorymodel'),
        ),
    ]
