# Generated by Django 5.1 on 2024-09-07 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_order_ordered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='ordered',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
